# See http://docs.spring.io/spring-boot/docs/current/reference/html/common-application-properties.html
spring:
  thymeleaf.cache: false
logging:
  level:
    org.springframework.web: TRACE
    guru.springframework.controllers: TRACE
    org.hibernate: TRACE
    com.inidus.platform: TRACE
cdr-connector:
  url: 'http://localhost:8080/ehrbase'
  username: ehrbase
  password: ehrbase
  is-token-auth: false
server:
  port: 8081


#spring:
#  profiles: marand
#cdr-connector:
#  url: 'https://test.operon.systems'
#  username: oprn_hcbox
#  password: XioTAJoO479
#  is-token-auth: false
#server:
#  port: 8082

#---
#spring:
#  profiles: ethercis
#cdr-connector:
#  url: 'http://178.62.71.220:8080'
#  username: guest
#  password: guest
#  is-token-auth: true
#server:
#  port: 8083